### ISSUE TITLE
Exception when filtering monitoring of learning plans

### ISSUE THREAD

**Issue by pete1854** [StudiUM/moodle-report_lpmonitoring#11] opened 2022-09-22 08:11 UTC
Hi,

When filtering in monitoring of learning plans I get a DB exception. Please see screenshot below.
We're running on Moodle 4.0.3+

![Skärmbild 2022-09-22 101240](https://user-images.githubusercontent.com/47314226/191697607-9dac7ddf-4f07-4873-9f82-a78147597af5.png)

The exception is thrown when I try to select a user.

The stack trace is as follows:

SQLState: 42000<br>
Error Code: 4104<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The multi-part identifier "uf1d_1.data" could not be bound.<br>

```
SELECT u.id,u.picture,u.firstname,u.lastname,u.firstnamephonetic,u.lastnamephonetic,u.middlename,u.alternatename,u.imagealt,u.email,u.username,u.department,u.institution, CONVERT(varchar(255),uf1d_1.data) AS profile_field_AID, p.id as planid, p.name as planname
                  FROM mdl_competency_plan p
                  JOIN mdl_user u ON u.id = p.userid
                 WHERE p.templateid = '16'
                       AND u.id <> '1' AND u.deleted = 0 AND u.confirmed = 1
              ORDER BY u.lastname, u.firstname, u.id
[array (
  0 => 16,
  1 => '1',
)]
Error code: dmlreadexception
* line 486 of \lib\dml\moodle_database.php: dml_read_exception thrown
* line 324 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
* line 431 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
* line 900 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
* line 465 of \report\lpmonitoring\classes\api.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
* line 166 of \report\lpmonitoring\classes\external.php: call to report_lpmonitoring\api::search_users_by_templateid()
* line 261 of \lib\externallib.php: call to report_lpmonitoring\external::search_users_by_templateid()
* line 81 of \lib\ajax\service.php: call to external_api::call_external_function()
```

**Comment by levemar** [comment] 2022-09-22 12:49
Hi @pete1854,
You can try to update the plugin to the last version, which was realeased yesterday (plugin version 2021111000, or 1.5.0). This version was only tested with Moodle 3.11, but it might still work with 4.0. We do not have a version specifically for Moodle 4.0 yet :(
Please let me know if it solved your problem.
Thanks,
Marie-Eve

**Comment by leblangi** [comment] 2024-03-01 19:52
Hello, due to the lack of answer, I am closing the ticket. Please reopen another one if the problem persists, adding as much detail as possible in order to be able to reproduce the problem.

**Comment by leblangi** [comment] 2024-03-01 19:53
Hello, due to the lack of answer, I am closing the ticket. Please reopen another one if the problem persists, adding as much detail as possible in order to be able to reproduce the problem.

**Comment by leblangi** [comment] 2024-03-01 19:53
Hello, due to the lack of answer, I am closing the ticket. Please reopen another one if the problem persists, adding as much detail as possible in order to be able to reproduce the problem.

**Closed as not planned by leblangi** 2024-03-01 19:53 UTC
